### ISSUE TITLE
제목 다르게나오는 이슈

### ISSUE THREAD

**Issue by taeunChoi** [yenoss/yenoss.github.io#1]
https://yenoss.github.io/swift/2017/05/10/Extension3.html
저자는 Extension3을 제목으로 의도한것 같지만 목록에선 Extension으로 나오고있음.    
또한 Extension제목이 이미 있어서 겹치는 현상발생.

**Comment by yenoss** [comment]
maybe..
it was my fault..  i wil fix it..

**Comment by taeunChoi** [comment]
awsome
